#!/usr/bin/zsh

# addind the zoxide configuration
eval "$(zoxide init zsh)"

debug "[fnm] start"
# adding fnm
zinit light "dominik-schwabe/zsh-fnm"
export ZSH_FNM_NODE_VERSION="24.1.0"
debug "[fnm] end"
