#!/usr/bin/zsh

# bun
export BUN_INSTALL="$HOME/.bun"

# Adding common binary paths
local_bin="$HOME/.local/bin/"
global_bin=/bin/
user_bin=/usr/bin/
user_local_bin=/usr/local/bin/

export GO_BIN="$HOME/go/bin/"

# Custom application build from source path
export CUSTOM_BUILD_PATH="$HOME/Documents/Applications/bin"

# custom scripts path 
export SCRIPT_DIR="$HOME/.config/.dotconfig/scripts"

export PATH="$PATH:$local_bin:$global_bin:$user_bin:$user_local_bin:$BUN_INSTALL/bin:$CUSTOM_BUILD_PATH:$GO_BIN:$SCRIPT_DIR"
