-- auto loads the configuration from lua/auto
require("utils.autoload")

-- vim.keymap.set( "n", "<leader>sf", function() 
-- end)
-- require("mini.pick").setup({
-- 	window = {
-- 		config = {
-- 			relative = "win",
-- 			row = 10,
-- 			col = 10,
-- 			width = 100,
-- 			height = 100,
-- 			border = { "╔", "═", "╗", "║", "╝", "═", "╚", "║" },
-- 		},
-- 		prompt_caret = "█",
-- 		prompt_prefix = "$> ",
-- 	},
-- 	mappings = {
-- 		choose_in_vsplit = "<c-v>",
-- 		choose_in_split = "<c-s>",
-- 		move_down = "<c-j>",
-- 		move_up = "<c-k>",
-- 	},
-- })
-- 
-- vim.keymap.set("n", "<leader>sf", function()
-- 	require("mini.pick").builtin.files()
-- end, { desc = "[S]earch [F]iles" })
-- 
-- vim.keymap.set("n", "<leader>sr", function()
-- 	vim.cmd("Pick resume")
-- end, { desc = "[S]earch [R]esume" })
-- 
-- vim.keymap.set("n", "<leader>sh", function()
-- 	vim.cmd("Pick help")
-- end, { desc = "[S]earch [H]elp" })
-- 
-- vim.keymap.set("n", "<leader>ss", function()
-- 	vim.cmd("Pick grep_live")
-- end, { desc = "[S]earch [S]tring" })
-- 
-- vim.keymap.set("n", "<leader>sg", function()
-- 	vim.cmd("Pick grep")
-- end, { desc = "[S]earch [G]rep" })
-- 
-- vim.keymap.set("n", "<leader>sb", function()
-- 	vim.cmd("Pick buffers")
-- end, { desc = "[S]earch [B]uffers" })
-- 
-- vim.keymap.set("n", "<leader>sb", function()
-- 	vim.cmd("Pick buffers")
-- end, { desc = "[S]earch [B]uffers" })
