# C(Capture the region) and c(copy to clicpboard)
bind=,Print,exec,grim -g "$(slurp)" - | wl-copy 
bind=$mainMod,Print,exec,grim -g "$(slurp)" - | swappy -f -

# using window + shift + b to zen browser.
binde = SUPER_SHIFT, b, exec, zen-beta 

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, Q, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, P, pseudo, 

# application shortcuts
bind = $mainMod, space, exec, $menu --allow-images
bind = SUPER_CTRL, space, exec, $HOME/.config/wofi/dmenu.sh
bind = SUPER_SHIFT, space, exec, $emojiMenu
bind = $mainMod, return, exec, $terminal 

# kills waybar
bind = $mainMod, w, exec, killall -SIGUSR1 .waybar-wrapped
