#!/usr/bin/zsh

open_notes() {
  sh "/home/saroj/.config/.dotconfig/bin/NotesOpener"
}

open_projects() {
  sh "/home/saroj/.config/bin/ProjectOpener"
}

open_git_remote() {
  sh "$HOME/.config/.dotconfig/scripts/xdg-opener.sh"
}

toggle_minimal_prompt() {
  if [[ $MINIMAL_PROMPT == true ]]; then
    export MINIMAL_PROMPT=false
    echo "Minimal prompt disabled!!"
  else
    export MINIMAL_PROMPT=true
    echo "Minimal prompt Activated!!"
  fi
}
# https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Keymaps
zle -N notes_opener open_notes
zle -N project_opener open_projects
zle -N minimal_prompt toggle_minimal_prompt
zle -N git_remote open_git_remote 

bindkey  '^n' notes_opener
bindkey  '^f' project_opener
bindkey  '^p' minimal_prompt
bindkey  '^g' git_remote

# adding the fzf keybindings
eval "$(fzf --zsh)"
